version: '2'
services:

  backend:
    build: ./backend
    command: node index.js
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/usr/app/src
    environment:
      server_port: 3001
      server_address: localhost

      db_host: postgres
      db_user: asd
      db_pass: asd
      db_name: asd

  frontend:
    build:
      context: ./frontend
      args:
        ulimit: nofile=262144:262144
    command: yarn start
    ports:
      - 3000:3000
    links:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules
    environment:
      NODE_ENV: development
      # TODO: socket url configuration

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: asd
      POSTGRES_PASSWORD: asd
      POSTGRES_DB: asd

volumes:
  postgres-data: {}