version: '2'
services:

  backend_dev:
    build: ./backend
    command: node index.js
    ports:
      - 3001:3001
    volumes:
      - ./backend/src:/usr/app/src
    environment:
      server_port: 3001
      server_address: localhost

  frontend_dev:
    build:
      context: ./frontend
    command: yarn start
    ports:
      - 3000:3000
    links:
      - backend_dev
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      NODE_ENV: development
      REACT_APP_SOCKET_URL: 'ws://localhost:3001/socket'

  prod_build:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      server_port: 3001
      # server_address: vessanseina.mntsr.com
      # REACT_APP_SOCKET_URL: ws://vessanseina.mntsr.com/socket


# volumes:
#   postgres-data: {}